# name: Continuous Integration

# on: 
#   pull_request:
#     branches:
#       - master

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: ['14.x', '20.x']

#     services:
#       postgres:
#         image: postgres
#         env:
#           POSTGRES_USER: ${{ secrets.PG_USER }}
#           POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
#           POSTGRES_DB: ${{ secrets.PG_DATABASE }}
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5
#         ports:
#           - 5432:5432

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v2
#       with:
#         node-version: ${{ matrix.node-version }}
#     - name: Install, migrate, and test
#       run: |
#         npm install
#         npm run migrate up
#         npm run test
#       env:
#         CI: true
#         HOST: localhost
#         PORT: 5000
#         PGHOST: localhost
#         PGPORT: 5432
#         PGUSER: ${{ secrets.PG_USER }}
#         PGPASSWORD: ${{ secrets.PG_PASSWORD }}
#         PGDATABASE: ${{ secrets.PG_DATABASE }}
#         ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
#         REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
#         ACCESS_TOKEN_AGE: ${{ secrets.ACCESS_TOKEN_AGE }}